/* generated by rust_qt_binding_generator */
use libc::{c_char, c_ushort, c_int};
use std::slice;
use std::char::decode_utf16;

use std::sync::Arc;
use std::sync::atomic::{AtomicPtr, Ordering};
use std::ptr::null;

use crate::implementation::*;


#[repr(C)]
pub struct COption<T> {
    data: T,
    some: bool,
}

impl<T> COption<T> {
    #![allow(dead_code)]
    fn into(self) -> Option<T> {
        if self.some {
            Some(self.data)
        } else {
            None
        }
    }
}

impl<T> From<Option<T>> for COption<T>
where
    T: Default,
{
    fn from(t: Option<T>) -> COption<T> {
        if let Some(v) = t {
            COption {
                data: v,
                some: true,
            }
        } else {
            COption {
                data: T::default(),
                some: false,
            }
        }
    }
}


pub enum QString {}

fn set_string_from_utf16(s: &mut String, str: *const c_ushort, len: c_int) {
    let utf16 = unsafe { slice::from_raw_parts(str, to_usize(len)) };
    let characters = decode_utf16(utf16.iter().cloned())
        .map(|r| r.unwrap());
    s.clear();
    s.extend(characters);
}



#[repr(C)]
#[derive(PartialEq, Eq, Debug)]
pub enum SortOrder {
    Ascending = 0,
    Descending = 1,
}

#[repr(C)]
pub struct QModelIndex {
    row: c_int,
    internal_id: usize,
}


fn to_usize(n: c_int) -> usize {
    if n < 0 {
        panic!("Cannot cast {} to usize", n);
    }
    n as usize
}


fn to_c_int(n: usize) -> c_int {
    if n > c_int::max_value() as usize {
        panic!("Cannot cast {} to c_int", n);
    }
    n as c_int
}


pub struct GrepQObject {}

pub struct GrepEmitter {
    qobject: Arc<AtomicPtr<GrepQObject>>,
    busy_changed: fn(*mut GrepQObject),
    query_changed: fn(*mut GrepQObject),
    new_data_ready: fn(*mut GrepQObject),
}

unsafe impl Send for GrepEmitter {}

impl GrepEmitter {
    /// Clone the emitter
    ///
    /// The emitter can only be cloned when it is mutable. The emitter calls
    /// into C++ code which may call into Rust again. If emmitting is possible
    /// from immutable structures, that might lead to access to a mutable
    /// reference. That is undefined behaviour and forbidden.
    pub fn clone(&mut self) -> GrepEmitter {
        GrepEmitter {
            qobject: self.qobject.clone(),
            busy_changed: self.busy_changed,
            query_changed: self.query_changed,
            new_data_ready: self.new_data_ready,
        }
    }
    fn clear(&self) {
        let n: *const GrepQObject = null();
        self.qobject.store(n as *mut GrepQObject, Ordering::SeqCst);
    }
    pub fn busy_changed(&mut self) {
        let ptr = self.qobject.load(Ordering::SeqCst);
        if !ptr.is_null() {
            (self.busy_changed)(ptr);
        }
    }
    pub fn query_changed(&mut self) {
        let ptr = self.qobject.load(Ordering::SeqCst);
        if !ptr.is_null() {
            (self.query_changed)(ptr);
        }
    }
    pub fn new_data_ready(&mut self) {
        let ptr = self.qobject.load(Ordering::SeqCst);
        if !ptr.is_null() {
            (self.new_data_ready)(ptr);
        }
    }
}

#[derive(Clone)]
pub struct GrepList {
    qobject: *mut GrepQObject,
    layout_about_to_be_changed: fn(*mut GrepQObject),
    layout_changed: fn(*mut GrepQObject),
    data_changed: fn(*mut GrepQObject, usize, usize),
    begin_reset_model: fn(*mut GrepQObject),
    end_reset_model: fn(*mut GrepQObject),
    begin_insert_rows: fn(*mut GrepQObject, usize, usize),
    end_insert_rows: fn(*mut GrepQObject),
    begin_move_rows: fn(*mut GrepQObject, usize, usize, usize),
    end_move_rows: fn(*mut GrepQObject),
    begin_remove_rows: fn(*mut GrepQObject, usize, usize),
    end_remove_rows: fn(*mut GrepQObject),
}

impl GrepList {
    pub fn layout_about_to_be_changed(&mut self) {
        (self.layout_about_to_be_changed)(self.qobject);
    }
    pub fn layout_changed(&mut self) {
        (self.layout_changed)(self.qobject);
    }
    pub fn data_changed(&mut self, first: usize, last: usize) {
        (self.data_changed)(self.qobject, first, last);
    }
    pub fn begin_reset_model(&mut self) {
        (self.begin_reset_model)(self.qobject);
    }
    pub fn end_reset_model(&mut self) {
        (self.end_reset_model)(self.qobject);
    }
    pub fn begin_insert_rows(&mut self, first: usize, last: usize) {
        (self.begin_insert_rows)(self.qobject, first, last);
    }
    pub fn end_insert_rows(&mut self) {
        (self.end_insert_rows)(self.qobject);
    }
    pub fn begin_move_rows(&mut self, first: usize, last: usize, destination: usize) {
        (self.begin_move_rows)(self.qobject, first, last, destination);
    }
    pub fn end_move_rows(&mut self) {
        (self.end_move_rows)(self.qobject);
    }
    pub fn begin_remove_rows(&mut self, first: usize, last: usize) {
        (self.begin_remove_rows)(self.qobject, first, last);
    }
    pub fn end_remove_rows(&mut self) {
        (self.end_remove_rows)(self.qobject);
    }
}

pub trait GrepTrait {
    fn new(emit: GrepEmitter, model: GrepList) -> Self;
    fn emit(&mut self) -> &mut GrepEmitter;
    fn busy(&self) -> bool;
    fn query(&self) -> &str;
    fn set_query(&mut self, value: String);
    fn row_count(&self) -> usize;
    fn insert_rows(&mut self, _row: usize, _count: usize) -> bool { false }
    fn remove_rows(&mut self, _row: usize, _count: usize) -> bool { false }
    fn can_fetch_more(&self) -> bool {
        false
    }
    fn fetch_more(&mut self) {}
    fn sort(&mut self, _: u8, _: SortOrder) {}
    fn line(&self, index: usize) -> &str;
    fn name(&self, index: usize) -> String;
    fn path(&self, index: usize) -> String;
}

#[no_mangle]
pub extern "C" fn grep_new(
    grep: *mut GrepQObject,
    grep_busy_changed: fn(*mut GrepQObject),
    grep_query_changed: fn(*mut GrepQObject),
    grep_new_data_ready: fn(*mut GrepQObject),
    grep_layout_about_to_be_changed: fn(*mut GrepQObject),
    grep_layout_changed: fn(*mut GrepQObject),
    grep_data_changed: fn(*mut GrepQObject, usize, usize),
    grep_begin_reset_model: fn(*mut GrepQObject),
    grep_end_reset_model: fn(*mut GrepQObject),
    grep_begin_insert_rows: fn(*mut GrepQObject, usize, usize),
    grep_end_insert_rows: fn(*mut GrepQObject),
    grep_begin_move_rows: fn(*mut GrepQObject, usize, usize, usize),
    grep_end_move_rows: fn(*mut GrepQObject),
    grep_begin_remove_rows: fn(*mut GrepQObject, usize, usize),
    grep_end_remove_rows: fn(*mut GrepQObject),
) -> *mut Grep {
    let grep_emit = GrepEmitter {
        qobject: Arc::new(AtomicPtr::new(grep)),
        busy_changed: grep_busy_changed,
        query_changed: grep_query_changed,
        new_data_ready: grep_new_data_ready,
    };
    let model = GrepList {
        qobject: grep,
        layout_about_to_be_changed: grep_layout_about_to_be_changed,
        layout_changed: grep_layout_changed,
        data_changed: grep_data_changed,
        begin_reset_model: grep_begin_reset_model,
        end_reset_model: grep_end_reset_model,
        begin_insert_rows: grep_begin_insert_rows,
        end_insert_rows: grep_end_insert_rows,
        begin_move_rows: grep_begin_move_rows,
        end_move_rows: grep_end_move_rows,
        begin_remove_rows: grep_begin_remove_rows,
        end_remove_rows: grep_end_remove_rows,
    };
    let d_grep = Grep::new(grep_emit, model);
    Box::into_raw(Box::new(d_grep))
}

#[no_mangle]
pub unsafe extern "C" fn grep_free(ptr: *mut Grep) {
    Box::from_raw(ptr).emit().clear();
}

#[no_mangle]
pub unsafe extern "C" fn grep_busy_get(ptr: *const Grep) -> bool {
    (&*ptr).busy()
}

#[no_mangle]
pub unsafe extern "C" fn grep_query_get(
    ptr: *const Grep,
    p: *mut QString,
    set: fn(*mut QString, *const c_char, c_int),
) {
    let o = &*ptr;
    let v = o.query();
    let s: *const c_char = v.as_ptr() as (*const c_char);
    set(p, s, to_c_int(v.len()));
}

#[no_mangle]
pub unsafe extern "C" fn grep_query_set(ptr: *mut Grep, v: *const c_ushort, len: c_int) {
    let o = &mut *ptr;
    let mut s = String::new();
    set_string_from_utf16(&mut s, v, len);
    o.set_query(s);
}

#[no_mangle]
pub unsafe extern "C" fn grep_row_count(ptr: *const Grep) -> c_int {
    to_c_int((&*ptr).row_count())
}
#[no_mangle]
pub unsafe extern "C" fn grep_insert_rows(ptr: *mut Grep, row: c_int, count: c_int) -> bool {
    (&mut *ptr).insert_rows(to_usize(row), to_usize(count))
}
#[no_mangle]
pub unsafe extern "C" fn grep_remove_rows(ptr: *mut Grep, row: c_int, count: c_int) -> bool {
    (&mut *ptr).remove_rows(to_usize(row), to_usize(count))
}
#[no_mangle]
pub unsafe extern "C" fn grep_can_fetch_more(ptr: *const Grep) -> bool {
    (&*ptr).can_fetch_more()
}
#[no_mangle]
pub unsafe extern "C" fn grep_fetch_more(ptr: *mut Grep) {
    (&mut *ptr).fetch_more()
}
#[no_mangle]
pub unsafe extern "C" fn grep_sort(
    ptr: *mut Grep,
    column: u8,
    order: SortOrder,
) {
    (&mut *ptr).sort(column, order)
}

#[no_mangle]
pub unsafe extern "C" fn grep_data_line(
    ptr: *const Grep, row: c_int,
    d: *mut QString,
    set: fn(*mut QString, *const c_char, len: c_int),
) {
    let o = &*ptr;
    let data = o.line(to_usize(row));
    let s: *const c_char = data.as_ptr() as (*const c_char);
    set(d, s, to_c_int(data.len()));
}

#[no_mangle]
pub unsafe extern "C" fn grep_data_name(
    ptr: *const Grep, row: c_int,
    d: *mut QString,
    set: fn(*mut QString, *const c_char, len: c_int),
) {
    let o = &*ptr;
    let data = o.name(to_usize(row));
    let s: *const c_char = data.as_ptr() as (*const c_char);
    set(d, s, to_c_int(data.len()));
}

#[no_mangle]
pub unsafe extern "C" fn grep_data_path(
    ptr: *const Grep, row: c_int,
    d: *mut QString,
    set: fn(*mut QString, *const c_char, len: c_int),
) {
    let o = &*ptr;
    let data = o.path(to_usize(row));
    let s: *const c_char = data.as_ptr() as (*const c_char);
    set(d, s, to_c_int(data.len()));
}
